# kubectl create job --from=cronjob/sysdig-vm-import sysdig-vm-import-manual
apiVersion: batch/v1
kind: CronJob
metadata:
  name: sysdig-vm-import-job
  namespace: sysdig-vm-reporting
spec:
  timeZone: 'Australia/Sydney' 
  schedule: "CRON_TZ=Australia/Sydney 30 9 * * *" # CRON_TZ for 1.24 or lower, not officially supported. Remove if on 1.25+
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: sysdig-vm-import-job
            image: ghcr.io/andrewd-sysdig/sysdig-vm-importer:2
            imagePullPolicy: IfNotPresent
            env:
            - name: BATCH_SIZE
              value: "100000"
            - name: REPORT_SCHEDULE_ID
              value: "2H3Sl0FjEkIocMkVAIfq6CFRSD6" # Report Schedule ID comes from Sysdig UI, click your "All Vulnerabilities" report and grab the Schedule ID from the URL bar
            - name: SYSDIG_SECURE_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: sysdig-secure-api-token
                  key: SYSDIG_SECURE_API_TOKEN
            - name: SYSDIG_REGION_URL
              value: "https://app.au1.sysdig.com" # Your Sysdig Region URL
            - name: ALL_VULNS_TABLE_NAME
              value: "all_vulns" # Name of the table to use in clickhouse to store the vulnerability data
            - name: CLICKHOUSE_HOSTNAME
              value: "clickhouse" # Only need to change if you change the cluster IP svc name
            - name: CLICKHOUSE_USER
              value: "sysdig_vm_user" # Username for Clickhouse DB
            - name: CLICKHOUSE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: clickhouse-password
                  key: CLICKHOUSE_PASSWORD
            args: ['0'] # This tells it to load the last report
          restartPolicy: OnFailure