---
apiVersion: v1
kind: Service
metadata:
  name: clickhouse
  namespace: sysdig-vm-reporting
  labels:
    app: clickhouse
spec:
  ports:
  - port: 8123
    name: "http-connection"
  - port: 9000
    name: "native-connection"
#  clusterIP: None
  selector:
    app: clickhouse
  type: LoadBalancer