{
 "title": "Sysdig VM Dashboard - All",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   { "name": "all_vulns_table", "query": "all_vulns" },
   {
    "name": "FromDate",
    "query": "select distinct toString(report_date) as report_date from $all_vulns_table"
   },
   {
    "name": "ToDate",
    "query": "select distinct toString(report_date) as report_date from $all_vulns_table"
   },
   {
    "name": "WorkloadType",
    "query": "select distinct k8s_workload_type from $all_vulns_table"
   }
  ]
 },
 "panels": [
  {
   "title": "Fixed Vulnerabilities",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "WITH vulns AS (\nselect distinct(unique_hash),severity from ${all_vulns_table} where report_date='${FromDate}' and k8s_workload_type in (${WorkloadType})\nEXCEPT\nselect distinct(unique_hash),severity from ${all_vulns_table} where report_date='${ToDate}'  and k8s_workload_type in (${WorkloadType})\n)\nselect count(*),severity from vulns group by severity ORDER BY severity='Negligible', severity='Low', severity='Medium', severity='High', severity='Critical'"
    }
   ]
  },
  {
   "title": "New Vulnerabilities",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "WITH vulns AS (\nselect distinct(unique_hash),severity from ${all_vulns_table} where report_date='${ToDate}' and k8s_workload_type in (${WorkloadType})\nEXCEPT\nselect distinct(unique_hash),severity from ${all_vulns_table} where report_date='${FromDate}' and k8s_workload_type in (${WorkloadType})\n)\nselect count(*),severity from vulns group by severity ORDER BY severity='Negligible', severity='Low', severity='Medium', severity='High', severity='Critical'"
    }
   ]
  },
  {
   "title": "Total Vulnerabilities",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT COUNT(distinct unique_hash),cast(report_date as timestamp) AS report_date from ${all_vulns_table} where severity='Critical' and k8s_workload_type in (${WorkloadType}) group by report_date"
    },
    {
     "rawSql": "SELECT COUNT(distinct unique_hash),cast(report_date as timestamp) AS report_date from ${all_vulns_table} where severity='High' and k8s_workload_type in (${WorkloadType}) group by report_date\n"
    },
    {
     "rawSql": "SELECT COUNT(distinct unique_hash),cast(report_date as timestamp) AS report_date from ${all_vulns_table} where severity='Medium' and k8s_workload_type in (${WorkloadType}) group by report_date\n"
    },
    {
     "rawSql": "SELECT COUNT(distinct unique_hash),cast(report_date as timestamp) AS report_date from ${all_vulns_table} where severity='Low' and k8s_workload_type in (${WorkloadType}) group by report_date\n"
    },
    {
     "rawSql": "SELECT COUNT(distinct unique_hash),cast(report_date as timestamp) AS report_date from ${all_vulns_table} where severity='Negligible' and k8s_workload_type in (${WorkloadType}) group by report_date\n"
    }
   ]
  }
 ]
}